tools:
    pylint:
        python_version: 3    
        config_file: '.pylintrc'
    
build:
    tests:
        before:
            - pip3 install pylint
        override:
            -
                command: 'pylint  ./libs  --output-format=parseable  --reports=n --include-naming-hint=y | tee pylint-data'
                analysis:
                    file: 'pylint-data'
                    format: 'pylint-parseable'
