build:
    tests:
        before:
            - pip3 install pylint
        override: 
            -
                command: 'pylint  ./ '
                analysis:
                    file: 'pylint_result.json'
                    format: 'pylint-json'
