build:
    tests:
        before:
            - pip3 install pylint
        override: 
            -
                command: 'pylint  ./ --reports=n --include-naming-hint=y'
                analysis:
                    file: 'pylint_result.json'
                    format: 'pylint-json'
