tools:
    pylint: true
    
build:
    tests:
        override:
            -
                command: 'pylint  ./libs  --output-format=parseable  --reports=n --include-naming-hint=y | tee pylint-data'
                analysis:
                    file: 'pylint-data'
                    format: 'pylint-parseable'
